---
title: "RuleKit classification example"
author: "Wojciech Sikora"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(rulekit)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Classification example

## Data

In this case data will be used in 10-fold cross-validation. Note that in this case, arguments train_data and test_data are lists of data frames instead of single data frames. Here you can see a sample of original data used in this example.

```{r, include=TRUE, results='asis', message=FALSE, warning=FALSE}
knitr::kable(head(seismic_bumps, 10))
folds<-caret::createFolds(seismic_bumps$class,10)
fold_list <- lapply(folds, function(x,y) y[x,],y=seismic_bumps)
train_data <- list()
test_data <- list()
for (i in 1:length(fold_list)) {
  test_data[i] <- fold_list[i]
  train_data[[i]] <- data.frame(data.table::rbindlist(fold_list[-i]))
}
formula <- class ~ .
control <- list(min_rule_covered = 6,
                induction_measure = 'GMeasure',
                pruning_measure = 'GMeasure',
                max_growing = 5)
results <- learn_rules(formula,control,train_data,test_data)
perf <- results[["test-performance"]]
rules <- results[["rules"]]
```
## Results
```{r}
knitr::kable(perf)
cat(head(rules,30),sep = "\n")
```
